<?php

/**
 * @file
 * Contains activity_basics.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityPublishedInterface;
use Drupal\node\NodeInterface;
use Drupal\group\Entity\GroupContent;
use Drupal\hux\Event\EntityEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

/**
 * Implements hook_entity_insert().
 */
function activity_basics_entity_insert(EntityInterface $entity): void {
  \Drupal::service('event_dispatcher')->dispatch(new EntityEvent($entity), EntityEvent::INSERT);
}

/**
 * Implements hook_entity_update().
 */
function activity_basics_entity_update(EntityInterface $entity): void {
  \Drupal::service('event_dispatcher')->dispatch(new EntityEvent($entity), EntityEvent::UPDATE);
}

/**
 * Implements hook_entity_presave().
 */
function activity_basics_entity_presave(EntityInterface $entity): void {
  \Drupal::service('event_dispatcher')->dispatch(new EntityEvent($entity), EntityEvent::PRESAVE);
}

/**
 * Implements hook_social_group_move().
 */
function activity_basics_social_group_move(NodeInterface $node): void {
  \Drupal::service('event_dispatcher')->dispatch(new EntityEvent($node), 'social_group_move');
}
